version: '3.1'

services:
    web:
        build:
            context: .
            dockerfile: deployment/Dockerfile.web
        command: gunicorn --bind 0.0.0.0:5000 wsgi:app
        image: lsapan/docker-swarm-demo-web
        links:
            - redis

    nginx:
        build:
            context: .
            dockerfile: deployment/Dockerfile.nginx
        image: lsapan/docker-swarm-demo-nginx
        links:
            - web
        ports:
            - 8000:80

    redis:
        image: redis
